/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Health'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** In-app notifications for the caller (unread count + recent items) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              unread: number;
              items: {
                /** Format: uuid */
                id: string;
                kind: string;
                body: string;
                read: boolean;
                /** Format: date-time */
                createdAt: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark all notifications read */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Marked read */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/marketing/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Active banners for a placement (WEB/MOBILE) */
    get: {
      parameters: {
        query?: {
          placement?: 'WEB' | 'MOBILE';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              id: string;
              title: string;
              body?: string | null;
              imageUrl?: string | null;
              linkUrl?: string | null;
              placement: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register with email + password (18+ age gate enforced) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RegisterRequest'];
        };
      };
      responses: {
        201: components['responses']['AuthTokens'];
        400: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with email/handle + password */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        200: components['responses']['AuthTokens'];
        401: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate refresh token (reuse detection revokes the family) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            refreshToken: string;
          };
        };
      };
      responses: {
        200: components['responses']['AuthTokens'];
        401: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a refresh token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Revoked (idempotent) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/oauth/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a Google/Apple identity token for Grid tokens */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: 'google' | 'apple';
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            idToken: string;
          };
        };
      };
      responses: {
        200: components['responses']['AuthTokens'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update profile */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UserUpdate'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
      };
    };
    trace?: never;
  };
  '/users/{handle}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public profile by handle */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          handle: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PublicProfile'];
          };
        };
        404: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}/follow': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Follow a creator */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Followed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Unfollow */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unfollowed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Discover feed (live now, filterable by category) */
    get: {
      parameters: {
        query?: {
          category?: string;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Stream'][];
              nextCursor?: string | null;
            };
          };
        };
      };
    };
    put?: never;
    /** Create a stream (Go Live setup — visibility, access, PPV price) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['StreamCreate'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Stream'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream details (gate metadata included; media token NOT included) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Stream'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mint a LiveKit join token — ONLY after entitlement check (ADR 0004, §3.4) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Short-lived LiveKit access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              token: string;
              /** @description LiveKit server URL */
              url: string;
            };
          };
        };
        /** @description Gated: purchase or subscription required */
        402: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        403: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/go-live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition own stream to LIVE (creates the media room when configured) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Live */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        403: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/chat/{messageId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Creator moderation: hide a chat message in your own stream */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          messageId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Hidden and broadcast as removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/mute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creator moderation: mute a viewer in your stream for N minutes */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            userId: string;
            minutes: number;
          };
        };
      };
      responses: {
        /** @description Muted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/mute/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Creator moderation: unmute a viewer */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unmuted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/slow-mode': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creator moderation: set slow-mode seconds (0 disables) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            seconds: number;
          };
        };
      };
      responses: {
        /** @description Slow-mode set */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/end': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End own stream */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ended */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Balances (derived from the ledger, never client-side) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WalletBalances'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wallet/packages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Diamond top-up packages (server-authoritative prices) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DiamondPackage'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wallet/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Transaction history */
    get: {
      parameters: {
        query?: {
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['WalletTransaction'][];
              nextCursor?: string | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/wallet/topup/checkout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a Stripe Checkout session for a diamond package (web channel)
     * @description Diamonds are credited by the Stripe webhook only (§3.3) — never by this endpoint's response.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            packageId: string;
          };
        };
      };
      responses: {
        /** @description Checkout session */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              checkoutUrl: string;
            };
          };
        };
        400: components['responses']['Error'];
        503: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/gifts/catalog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server-driven gift catalog */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GiftCatalogItem'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/gifts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a gift (ledger tx — viewer diamonds → creator coins + platform fee) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            giftId: string;
            qty: number;
            /** Format: uuid */
            idempotencyKey: string;
          };
        };
      };
      responses: {
        /** @description Gift sent; broadcast via WS gift:sent */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description caller balance after */
              diamonds: number;
              combo: number;
            };
          };
        };
        404: components['responses']['Error'];
        /** @description Insufficient diamonds */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/top-gifters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Top three gifters of a live stream (session-scoped) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              userId: string;
              handle: string;
              total: number;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/gates/{streamId}/unlock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** PPV unlock (ledger tx + stream_access_grant; idempotency is server-derived per viewer+stream) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          streamId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unlocked — grant persisted (idempotent) */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              unlocked: boolean;
              /** @description balance after */
              diamonds: number;
            };
          };
        };
        400: components['responses']['Error'];
        /** @description Insufficient diamonds */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/streams/{id}/invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creator invites a viewer into a private stream (INVITE grant) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            handle: string;
          };
        };
      };
      responses: {
        /** @description Invited (idempotent) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payments/webhooks/stripe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stripe webhook (signature-verified, idempotent crediting) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Processed or already processed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payments/webhooks/revenuecat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** RevenueCat webhook (signature-verified, idempotent crediting) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Processed or already processed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions/price': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Creator sets/clears their own monthly subscription price */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            priceCents: number | null;
          };
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions/{creatorId}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Caller's subscription status to a creator */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          creatorId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              creatorId: string;
              active: boolean;
              /** Format: date-time */
              renewsAt: string | null;
              priceCents: number | null;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions/{creatorId}/checkout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Subscribe to a creator (Stripe Billing checkout) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          creatorId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Checkout session */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              checkoutUrl: string;
            };
          };
        };
        400: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/subscriptions/{creatorId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Cancel at period end */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          creatorId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Canceled at period end */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payouts/connect/onboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start/resume Stripe Connect Express onboarding */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Hosted onboarding link */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              url: string;
            };
          };
        };
        503: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payouts/connect/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Connect/KYC status + payout parameters for the caller */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              connected: boolean;
              payoutsEnabled: boolean;
              /** @enum {string} */
              kycStatus: 'NONE' | 'PENDING' | 'VERIFIED' | 'REJECTED';
              /** Format: date-time */
              holdUntil: string | null;
              minPayoutCoins: number;
              coinValueCents: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payouts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My payout history */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PayoutItem'][];
          };
        };
      };
    };
    put?: never;
    /** Request a payout (debits coins into clearing; approval triggers the transfer) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            coinAmount: number;
            /** Format: uuid */
            idempotencyKey: string;
          };
        };
      };
      responses: {
        /** @description Payout requested */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PayoutItem'];
          };
        };
        400: components['responses']['Error'];
        403: components['responses']['Error'];
        /** @description Insufficient coins */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Phase 8 */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description stub */
        501: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: 'ok';
      service: string;
      /** Format: date-time */
      timestamp: string;
    };
    Error: {
      statusCode: number;
      message: string;
      /** @description machine-readable error code */
      code?: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
      handle: string;
      /**
       * Format: date
       * @description 18+ enforced server-side
       */
      dob: string;
      country?: string;
    };
    LoginRequest: {
      /** @description email or handle */
      identifier: string;
      password: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      handle: string;
      email: string | null;
      displayName: string | null;
      avatarUrl: string | null;
      bio: string | null;
      /** @enum {string} */
      role: 'USER' | 'CREATOR';
      /** @enum {string} */
      status: 'ACTIVE' | 'SUSPENDED' | 'BANNED' | 'DELETED';
      /** Format: date-time */
      createdAt: string;
    };
    UserUpdate: {
      displayName?: string;
      avatarUrl?: string;
      bio?: string;
    };
    PublicProfile: {
      /** Format: uuid */
      id: string;
      handle: string;
      displayName?: string | null;
      avatarUrl?: string | null;
      bio?: string | null;
      followerCount?: number;
      isLive?: boolean;
    };
    StreamCreate: {
      title: string;
      category?: string;
      /**
       * @default PUBLIC
       * @enum {string}
       */
      visibility: 'PUBLIC' | 'FOLLOWERS' | 'PRIVATE';
      /**
       * @default FREE
       * @enum {string}
       */
      access: 'FREE' | 'PPV' | 'SUBS';
      /** @description required when access=ppv */
      ppvPriceDiamonds?: number;
    };
    Stream: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      creatorId: string;
      creatorHandle?: string;
      title: string;
      category?: string | null;
      thumbnailUrl?: string | null;
      /** @enum {string} */
      visibility: 'PUBLIC' | 'FOLLOWERS' | 'PRIVATE';
      /** @enum {string} */
      access: 'FREE' | 'PPV' | 'SUBS';
      ppvPriceDiamonds?: number | null;
      /** @enum {string} */
      status: 'SCHEDULED' | 'LIVE' | 'ENDED';
      viewerCount?: number;
      /** Format: date-time */
      startedAt?: string | null;
      /** @description whether the caller may join (server-computed) */
      entitled?: boolean;
    };
    WalletBalances: {
      /** @description spendable balance (viewer currency) */
      diamonds: number;
      /** @description earned balance (creator currency) */
      coins: number;
    };
    WalletTransaction: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      kind: 'TOPUP' | 'GIFT' | 'PPV_UNLOCK' | 'SUB' | 'PAYOUT' | 'REFUND' | 'ADJUSTMENT';
      /** @description signed from the caller's perspective */
      amount?: number;
      /** @enum {string} */
      currency?: 'DIAMOND' | 'COIN';
      /** Format: date-time */
      createdAt: string;
    };
    PayoutItem: {
      /** Format: uuid */
      id: string;
      coinAmount: number;
      fiatAmountCents: number;
      fiatCurrency: string;
      /** @enum {string} */
      status: 'REQUESTED' | 'APPROVED' | 'PROCESSING' | 'PAID' | 'FAILED' | 'CANCELED';
      failureReason?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    DiamondPackage: {
      id: string;
      diamonds: number;
      bonus: number;
      usdCents: number;
    };
    GiftCatalogItem: {
      id: string;
      name: string;
      emoji?: string | null;
      assetUrl?: string | null;
      priceDiamonds: number;
      animationTier: number;
    };
  };
  responses: {
    /** @description Access + refresh token pair */
    AuthTokens: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          accessToken: string;
          refreshToken: string;
          user: components['schemas']['User'];
        };
      };
    };
    /** @description Error envelope */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
